// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DevBoost.ORM.App
{
    public partial class TbPosicao
    {
        public int IdPosicao { get; set; }
        public string Posicao { get; set; }
        public int? IdJogador { get; set; }

        public virtual TbJogador IdJogadorNavigation { get; set; }
    }
}